SOCIAL_PATTERNS = {
    "emails":         r"[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}",
    "twitter_x":      r"(?:https?://)?(?:www\.)?(?:twitter\.com|x\.com)/@?[A-Za-z0-9_]{1,50}",
    "instagram":      r"(?:https?://)?(?:www\.)?instagram\.com/@?[A-Za-z0-9_.]{1,50}",
    "tiktok":         r"(?:https?://)?(?:www\.)?tiktok\.com/@?[A-Za-z0-9_.]{1,50}",
    "facebook":       r"(?:https?://)?(?:www\.)?facebook\.com/(?:pages/)?[A-Za-z0-9_.\-/]{1,100}",
    "linkedin":       r"(?:https?://)?(?:www\.)?linkedin\.com/(?:in|company|school)/[A-Za-z0-9_\-]{1,100}",
    "twitch":         r"(?:https?://)?(?:www\.)?twitch\.tv/[A-Za-z0-9_]{1,50}",
    "discord":        r"(?:https?://)?discord\.(?:gg|com/invite)/[A-Za-z0-9_\-]{1,50}",
    "patreon":        r"(?:https?://)?(?:www\.)?patreon\.com/[A-Za-z0-9_]{1,50}",
    "youtube":        r"(?:https?://)?(?:www\.)?youtube\.com/(?:@|c/|channel/|user/)[A-Za-z0-9_\-]{1,100}",
    "snapchat":       r"(?:https?://)?(?:www\.)?snapchat\.com/add/[A-Za-z0-9_.]{1,50}",
    "pinterest":      r"(?:https?://)?(?:www\.)?pinterest\.com/[A-Za-z0-9_.]{1,50}",
    "threads":        r"(?:https?://)?(?:www\.)?threads\.net/@?[A-Za-z0-9_.]{1,50}",
    "spotify":        r"(?:https?://)?open\.spotify\.com/(?:user|artist|show)/[A-Za-z0-9_\-]{1,100}",
    "apple_podcasts": r"(?:https?://)?podcasts\.apple\.com/[^\s\"'<>]{1,200}",
    "soundcloud":     r"(?:https?://)?(?:www\.)?soundcloud\.com/[A-Za-z0-9_\-]{1,100}",
    "reddit":         r"(?:https?://)?(?:www\.)?reddit\.com/(?:r|u)/[A-Za-z0-9_]{1,50}",
    "github":         r"(?:https?://)?(?:www\.)?github\.com/[A-Za-z0-9_\-]{1,100}",
}